// TODO: with optional params

#[derive(Debug)]
pub enum Method {
    GetMe,
    LogOut,
    Close,
    SendMessage,
    ForwardMessage,
    CopyMessage,
    // SendPhoto,
    // SendAudio,
    // SendDocument,
    // SendVideo,
    // SendAnimation,
    // SendVoice,
    // SendVideoNote,
    // SendMediaGroup,
    // SendLocation,
    // SendVenue,
    // SendContract,
    // SendPoll,
    // SendDice,
    // SendChatAction,
    // GetUserProfilePhotos,
    // GetFile,
    // BanChatMember,
    // UnbanChatMember,
    // RestrictChatMember,
    // PromoteChatMember,
    // SetChatAdministratorCustomTitle,
    // BanChatSenderChat,
    // UnbanChatSenderChat,
    // SetChatPermissions,
    // ExportChatInviteLink,
    // CreateChatInviteLink,
    // EditChatInviteLink,
    // RevokeChatInviteLink,
    // ApproveChatJoinRequest,
    // DeclineChatJoinRequest,
    // SetChatPhoto,
    // DeleteChatPhoto,
    // SetChatTitle,
    // SetChatDescription,
    // PinChatMessage,
    // UnpinChatMessage,
    // UnpinAllChatMessages,
    // LeaveChat,
    // GetChat,
    // GetChatAdministrators,
    // GetChatMemberCount,
    // GetChatMember,
    // SetChatStickerSet,
    // DeleteChatStickerSet,
    // GetForumTopicIconStickers,
    // CreateForumTopic,
    // EditForumTopic,
    // CloseForumTopic,
    // ReopenForumTopic,
    // DeleteForumTopic,
    // UnpinAllForumTopicMessages,
    // EditGeneralForumTopic,
    // CloseGeneralForumTopic,
    // ReopenGeneralForumTopic,
    // HideGeneralForumTopic,
    // UnhideGeneralForumTopic,
    // AnswerCallbackQuery,
    // SetMyCommands,
    // DeleteMyCommands,
    // GetMyCommands,
    // SetMyDescription,
    // GetMyDescription,
    // SetMyShortDescription,
    // GetMyShortDescription,
    // SetChatMenuButton,
    // GetChatMenuButton,
    // SetMyDefaultAdministratorRights,
    // GetMyDefaultAdministratorRights,
}

impl ToString for Method {
    fn to_string(&self) -> String {
        match self {
            Method::GetMe => "getMe".to_string(),
            Method::LogOut => "logOut".to_string(),
            Method::Close => "close".to_string(),
            Method::SendMessage => "sendMessage".to_string(),
            Method::ForwardMessage => "forwardMessage".to_string(),
            Method::CopyMessage => "copyMessage".to_string(),
            // Method::SendPhoto => "sendPhoto".to_string(),
            // Method::SendAudio => "sendAudio".to_string(),
            // Method::SendDocument => "sendDocument".to_string(),
            // Method::SendVideo => todo!(),
            // Method::SendAnimation => todo!(),
            // Method::SendVoice => todo!(),
            // Method::SendVideoNote => todo!(),
            // Method::SendMediaGroup => todo!(),
            // Method::SendLocation => todo!(),
            // Method::SendVenue => todo!(),
            // Method::SendContract => todo!(),
            // Method::SendPoll => todo!(),
            // Method::SendDice => todo!(),
            // Method::SendChatAction => todo!(),
            // Method::GetUserProfilePhotos => todo!(),
            // Method::GetFile => todo!(),
            // Method::BanChatMember => todo!(),
            // Method::UnbanChatMember => todo!(),
            // Method::RestrictChatMember => todo!(),
            // Method::PromoteChatMember => todo!(),
            // Method::SetChatAdministratorCustomTitle => todo!(),
            // Method::BanChatSenderChat => todo!(),
            // Method::UnbanChatSenderChat => todo!(),
            // Method::SetChatPermissions => todo!(),
            // Method::ExportChatInviteLink => todo!(),
            // Method::CreateChatInviteLink => todo!(),
            // Method::EditChatInviteLink => todo!(),
            // Method::RevokeChatInviteLink => todo!(),
            // Method::ApproveChatJoinRequest => todo!(),
            // Method::DeclineChatJoinRequest => todo!(),
            // Method::SetChatPhoto => todo!(),
            // Method::DeleteChatPhoto => todo!(),
            // Method::SetChatTitle => todo!(),
            // Method::SetChatDescription => todo!(),
            // Method::PinChatMessage => todo!(),
            // Method::UnpinChatMessage => todo!(),
            // Method::UnpinAllChatMessages => todo!(),
            // Method::LeaveChat => todo!(),
            // Method::GetChat => todo!(),
            // Method::GetChatAdministrators => todo!(),
            // Method::GetChatMemberCount => todo!(),
            // Method::GetChatMember => todo!(),
            // Method::SetChatStickerSet => todo!(),
            // Method::DeleteChatStickerSet => todo!(),
            // Method::GetForumTopicIconStickers => todo!(),
            // Method::CreateForumTopic => todo!(),
            // Method::EditForumTopic => todo!(),
            // Method::CloseForumTopic => todo!(),
            // Method::ReopenForumTopic => todo!(),
            // Method::DeleteForumTopic => todo!(),
            // Method::UnpinAllForumTopicMessages => todo!(),
            // Method::EditGeneralForumTopic => todo!(),
            // Method::CloseGeneralForumTopic => todo!(),
            // Method::ReopenGeneralForumTopic => todo!(),
            // Method::HideGeneralForumTopic => todo!(),
            // Method::UnhideGeneralForumTopic => todo!(),
            // Method::AnswerCallbackQuery => todo!(),
            // Method::SetMyCommands => todo!(),
            // Method::DeleteMyCommands => todo!(),
            // Method::GetMyCommands => todo!(),
            // Method::SetMyDescription => todo!(),
            // Method::GetMyDescription => todo!(),
            // Method::SetMyShortDescription => todo!(),
            // Method::GetMyShortDescription => todo!(),
            // Method::SetChatMenuButton => todo!(),
            // Method::GetChatMenuButton => todo!(),
            // Method::SetMyDefaultAdministratorRights => todo!(),
            // Method::GetMyDefaultAdministratorRights => todo!(),
        }
    }
}
